### PR TITLE
30 valid date component

### PR DESCRIPTION
**Pull request by CJGutz**
closes: #30 

## Proposed changes
Created a component which displays the dates from and until for a VC.
Only the parent can decide if the VC is valid for the given dates.

## Screenshots
image
image

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added
- [x] Documentation have been written

### CODE REVIEW

**Comment by thomsen85** [comment]
image
Spacing between logo and writing is off

**Comment by thomsen85** [comment]
image
See also difference between weight and sizes on fonts for lables and values

**Comment by CJGutz** [comment]
> image See also difference between weight and sizes on fonts for lables and values

Just for reference. This is the difference between bold and semibold.

image

Updated to this:
image

**Review by thomsen85 — APPROVED** [review]
Move tests to __tests__ folder, and im happy, Great work

**Pull request merged**
